debug: false

server:
  port: 8081
#spring:
#  datasource:
#    url: jdbc:mysql://10.123.52.189:3306/oh_coupon
#    username: devdb
#    password: d^V$0Fu!/6-<
#    driver-class-name: com.mysql.jdbc.Driver

spring:
  thymeleaf:
    enabled: true
    cache: false
    suffix: .html

security:
  oauth2:
    client:
      client-id: app-1
      client-secret: 123456
    resource:
      token-info-uri: http://127.0.0.1:8080/oauth/token
    #      user-info-uri: http://127.0.0.1:8080/oauth/userinfo
    authorization:
      check-token-access: http://127.0.0.1:8080/oauth/check_token
